package id.lariss.store.domain;

import static id.lariss.store.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProductVariantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductVariantAllPropertiesEquals(ProductVariant expected, ProductVariant actual) {
        assertProductVariantAutoGeneratedPropertiesEquals(expected, actual);
        assertProductVariantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductVariantAllUpdatablePropertiesEquals(ProductVariant expected, ProductVariant actual) {
        assertProductVariantUpdatableFieldsEquals(expected, actual);
        assertProductVariantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductVariantAutoGeneratedPropertiesEquals(ProductVariant expected, ProductVariant actual) {
        assertThat(expected)
            .as("Verify ProductVariant auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductVariantUpdatableFieldsEquals(ProductVariant expected, ProductVariant actual) {
        assertThat(expected)
            .as("Verify ProductVariant relevant properties")
            .satisfies(e -> assertThat(e.getImageUrl()).as("check imageUrl").isEqualTo(actual.getImageUrl()))
            .satisfies(e -> assertThat(e.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getPrice()))
            .satisfies(e -> assertThat(e.getColor()).as("check color").isEqualTo(actual.getColor()))
            .satisfies(e -> assertThat(e.getProcessor()).as("check processor").isEqualTo(actual.getProcessor()))
            .satisfies(e -> assertThat(e.getMemory()).as("check memory").isEqualTo(actual.getMemory()))
            .satisfies(e -> assertThat(e.getStorage()).as("check storage").isEqualTo(actual.getStorage()))
            .satisfies(e -> assertThat(e.getScreen()).as("check screen").isEqualTo(actual.getScreen()))
            .satisfies(e -> assertThat(e.getConnectivity()).as("check connectivity").isEqualTo(actual.getConnectivity()))
            .satisfies(e -> assertThat(e.getMaterial()).as("check material").isEqualTo(actual.getMaterial()))
            .satisfies(e -> assertThat(e.getCaseSize()).as("check caseSize").isEqualTo(actual.getCaseSize()))
            .satisfies(e -> assertThat(e.getStrapColor()).as("check strapColor").isEqualTo(actual.getStrapColor()))
            .satisfies(e -> assertThat(e.getStrapSize()).as("check strapSize").isEqualTo(actual.getStrapSize()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductVariantUpdatableRelationshipsEquals(ProductVariant expected, ProductVariant actual) {
        assertThat(expected)
            .as("Verify ProductVariant relationships")
            .satisfies(e -> assertThat(e.getProduct()).as("check product").isEqualTo(actual.getProduct()));
    }
}
